"""
nnlib -- shared helpers to drive the NewtonianNoiseCA integrators.

Pure standard-library (no numpy), so it runs anywhere. It writes libconfig
configuration files from Python dicts, runs an integrator executable with
``--config``, and parses its three-column output ``f  sqrt_Sh  rel_err``.

The default parameter sets mirror ``etc/configuration_{isotropic,anisotropic}.cfg``.
"""

import os
import math
import csv
import subprocess
import tempfile

REPO_DIR  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# NN_BUILD_DIR lets a container build (or any out-of-tree build) live beside a
# native build/ without clashing.
BUILD_DIR = os.environ.get("NN_BUILD_DIR") or os.path.join(REPO_DIR, "build")
TWO_PI    = 2.0 * math.pi

# keys that must be emitted as libconfig ints / strings / bools (everything else
# is emitted as a float with an explicit decimal point, which libconfig requires
# for settings the C++ side reads with ``(double)``).
INT_KEYS  = {"Ncalls", "Niterations", "Npoints"}
STR_KEYS  = {"h_model"}
BOOL_KEYS = {"omega_log"}

DEFAULTS = {
    "isotropic": dict(
        Ncalls=500000, Niterations=50, MaxError=1.0e-8,
        alpha=1.0, psi=0.0, r0=1.0, u=10.0,
        min_phi=0.0, max_phi=TWO_PI,
        min_p=0.0, max_p=1.0,
        min_k=0.0, max_k=10000.0,
        omega_min=TWO_PI, omega_max=10.0 * TWO_PI, Npoints=100,
        h_model="gaussian", sigma_U=1.5, beta_sw=0.0, cTv2_ratio=1.0,
        omega_log=False,
    ),
    "anisotropic": dict(
        Ncalls=500000, Niterations=100, MaxError=1.0e-8,
        delta=1.0, T_star=1.0, psi=0.0, r0=5.0, u_star=1.0,
        min_x3=1.0, max_x3=10.0,
        min_z=0.0, max_z=1.0,
        min_k=0.0, max_k=10000.0,
        min_phi=0.0, max_phi=TWO_PI,
        omega_min=TWO_PI, omega_max=10.0 * TWO_PI, Npoints=100,
        h_model="analytic", sigma_U=1.5, beta_sw=0.0, cTv2_ratio=1.0,
        omega_log=False,
    ),
}


def _fmt(key, value):
    if key in STR_KEYS:
        return '{} = "{}";'.format(key, value)
    if key in BOOL_KEYS or isinstance(value, bool):
        return "{} = {};".format(key, "true" if value else "false")
    if key in INT_KEYS:
        return "{} = {};".format(key, int(value))
    s = "{:.15g}".format(float(value))
    if not any(c in s for c in ".eEni"):   # ensure a decimal point for libconfig floats
        s += ".0"
    return "{} = {};".format(key, s)


def write_config(path, params):
    """Write a params dict to a libconfig file at *path*."""
    with open(path, "w") as fh:
        fh.write("# generated by scripts/nnlib.py\n")
        for key, value in params.items():
            fh.write(_fmt(key, value) + "\n")


def binary(model, backend="tbb"):
    exe = os.path.join(BUILD_DIR, "Integrator_{}_{}".format(model, backend))
    if not os.path.exists(exe):
        raise FileNotFoundError(
            "{} not found -- build it first (make -C build Integrator_{}_{})"
            .format(exe, model, backend))
    return exe


def run(model, params, backend="tbb"):
    """Run one integrator invocation. Returns a list of (f, sqrt_Sh, rel_err)."""
    exe = binary(model, backend)
    with tempfile.NamedTemporaryFile("w", suffix=".cfg", delete=False) as tf:
        cfg_path = tf.name
    try:
        write_config(cfg_path, params)
        proc = subprocess.run([exe, "--config", cfg_path],
                              stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                              text=True)
        if proc.returncode != 0:
            raise RuntimeError("integrator failed (rc={}):\n{}"
                               .format(proc.returncode, proc.stderr))
        rows = []
        for line in proc.stdout.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            f = float(parts[0])
            sh = float(parts[1])
            err = float(parts[2]) if len(parts) > 2 else float("nan")
            rows.append((f, sh, err))
        return rows
    finally:
        os.unlink(cfg_path)


def freq_sweep(params, fmin, fmax, npoints, log=False):
    """Set the frequency sweep on *params* from Hz values (in place, returns it)."""
    params["omega_min"] = TWO_PI * fmin
    params["omega_max"] = TWO_PI * fmax
    params["Npoints"]   = int(npoints)
    params["omega_log"] = bool(log)
    return params


def scan(model, scan_key, scan_values, overrides=None, backend="tbb", verbose=True):
    """Vary one key over scan_values; return tidy rows (scan_val, f, sqrt_Sh, rel_err)."""
    base = dict(DEFAULTS[model])
    if overrides:
        base.update(overrides)
    rows = []
    for val in scan_values:
        p = dict(base)
        p[scan_key] = val
        pts = run(model, p, backend)
        worst = max((r[2] for r in pts if r[2] == r[2]), default=float("nan"))
        if verbose:
            print("  {}={:<12} points={:<4} worst rel_err={:.3g}"
                  .format(scan_key, val, len(pts), worst))
        for (f, sh, err) in pts:
            rows.append((val, f, sh, err))
    return rows


def write_csv(path, rows, scan_key):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow([scan_key, "f_Hz", "sqrt_Sh", "rel_err"])
        for r in rows:
            w.writerow(r)


def read_csv(path):
    """Read a tidy CSV written by write_csv. Returns (scan_key, list-of-dicts)."""
    with open(path) as fh:
        r = csv.reader(fh)
        header = next(r)
        scan_key = header[0]
        data = []
        for row in r:
            data.append(dict(scan_val=row[0],
                             f=float(row[1]),
                             sqrt_Sh=float(row[2]),
                             rel_err=float(row[3])))
    return scan_key, data
